version: '3.8'

services:
  atlas-nyc:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=nightlife.db
      - BASE_URL=https://atlas-nyc.com
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - atlas-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - atlas-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./uploads:/var/www/uploads
    depends_on:
      - atlas-nyc
    restart: unless-stopped
    networks:
      - atlas-network

volumes:
  redis_data:

networks:
  atlas-network:
    driver: bridge