services:
  # Web service for the API
  - type: web
    name: atlas-nyc-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: atlas-nyc-db
          property: connectionString
      - key: GOOGLE_MAPS_API_KEY
        sync: false  # You'll add this manually in Render dashboard
      - key: ALLOWED_ORIGINS
        value: '["https://atlas-nyc.onrender.com"]'
      - key: BASE_URL
        value: https://atlas-nyc.onrender.com
    autoDeploy: true
    healthCheckPath: /health

databases:
  # PostgreSQL database
  - name: atlas-nyc-db
    plan: starter  # Free tier - upgrade for production
    ipAllowList: []  # Allow connections from anywhere

# Environment groups (optional)
envVarGroups:
  - name: atlas-nyc-settings
    envVars:
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_UPLOAD_SIZE
        value: 10485760  # 10MB
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_PERIOD
        value: 60